//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_contest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _InviteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _InviteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mm_contest.Views.Invite._InviteResources", typeof(_InviteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear [FIRSTNAME],&lt;br /&gt;&lt;br /&gt;
        ///Your friend [INVITERFIRSTNAME] thought you would enjoy entering MAJESTA’s Trees of Knowledge competition. The only competition where one lucky school will win a $20,000 outdoor classroom† and you could have a chance to win $10,000*!  To learn more about this great contest, &lt;a href=&quot;[DOMAIN]?id=[GUID]&quot; style=&quot;color:#000;&quot;&gt;click here&lt;/a&gt;!.
        /// </summary>
        public static string EmailBody_InviteFriend {
            get {
                return ResourceManager.GetString("EmailBody_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;.
        /// </summary>
        public static string EmailFooter {
            get {
                return ResourceManager.GetString("EmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body bgcolor=&quot;#FFF&quot;&gt;.
        /// </summary>
        public static string EmailHeader {
            get {
                return ResourceManager.GetString("EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend wants you to vote in a contest!.
        /// </summary>
        public static string EmailSubjectLine_InviteFriend {
            get {
                return ResourceManager.GetString("EmailSubjectLine_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Invite_Button {
            get {
                return ResourceManager.GetString("Invite_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One additional ballot is received for each friend referred to a maximum of 10 friends..
        /// </summary>
        public static string Invite_PageContent {
            get {
                return ResourceManager.GetString("Invite_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends!.
        /// </summary>
        public static string Invite_PageTitle {
            get {
                return ResourceManager.GetString("Invite_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invitation email was sent to [FIRSTNAME]..
        /// </summary>
        public static string Invite_SentMsg {
            get {
                return ResourceManager.GetString("Invite_SentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this step.
        /// </summary>
        public static string Invite_Skip {
            get {
                return ResourceManager.GetString("Invite_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have invited &lt;strong&gt;{0}&lt;/strong&gt; friends and received &lt;strong&gt;{1}&lt;/strong&gt; extra entries..
        /// </summary>
        public static string Invite_TotalFriends {
            get {
                return ResourceManager.GetString("Invite_TotalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Denotes Required Field.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name field is required..
        /// </summary>
        public static string ValidationFirstName {
            get {
                return ResourceManager.GetString("ValidationFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name field is required..
        /// </summary>
        public static string ValidationLastName {
            get {
                return ResourceManager.GetString("ValidationLastName", resourceCulture);
            }
        }
    }
}
