//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_contest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mm_contest.Views.Home._HomeResources", typeof(_HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started!.
        /// </summary>
        public static string Index_Button {
            get {
                return ResourceManager.GetString("Index_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Modern Media contest template is built using the 960 grid system from &lt;a href=&quot;http://www.getskeleton.com&quot; target=&quot;_blank&quot;&gt;http://getskeleton.com&lt;/a&gt;.  Designers can download the &lt;a href=&quot;http://www.getskeleton.com/documentation-assets/Skeleton-Grid.psd.zip&quot; target=&quot;_blank&quot;&gt;&lt;strong&gt;960 grid PSD template&lt;/strong&gt;&lt;/a&gt;.&lt;/p&gt;&lt;p&gt;The syntax is simple and it&apos;s effective cross browser, but the awesome part is that it also has the flexibility to go mobile like a champ. &lt;strong&gt;Go ahead, resize the browser and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Index_PageContent {
            get {
                return ResourceManager.GetString("Index_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contest.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the &lt;a href=&quot;/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; and the &lt;a href=&quot;/Home/PrivacyPolicyPopUp&quot; class=&quot;privacyPopUp&quot;&gt;Privacy Policy&lt;/a&gt; and agree to be bound and abide by them..
        /// </summary>
        public static string LabelAcceptRules {
            get {
                return ResourceManager.GetString("LabelAcceptRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Privacy_PageContent {
            get {
                return ResourceManager.GetString("Privacy_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_PageTitle {
            get {
                return ResourceManager.GetString("Privacy_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;In eget velit libero. Donec laoreet tortor vitae felis lobortis scelerisque. Quisque eget sem id ante imperdiet facilisis. Aliquam tempor tincidunt vulputate. Proin feugiat commodo tellus non iaculis. Nulla est ante, convallis vel mollis vitae, egestas sed dui. Sed pellentesque gravida urna a ullamcorper. Fusce ut dui vitae orci porta ultricies molestie ac purus. Sed luctus, leo sit amet ultrices rutrum, lacus lorem euismod arcu, id tempus metus enim venenatis nulla. Quisque vitae ante diam, ut commodo s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Prize_PageContent {
            get {
                return ResourceManager.GetString("Prize_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string Prize_PageTitle {
            get {
                return ResourceManager.GetString("Prize_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Rules_PageContent {
            get {
                return ResourceManager.GetString("Rules_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest Rules.
        /// </summary>
        public static string Rules_PageTitle {
            get {
                return ResourceManager.GetString("Rules_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Official Rules..
        /// </summary>
        public static string ValidationAgreeRules {
            get {
                return ResourceManager.GetString("ValidationAgreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
    }
}
