//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_contest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mm_contest.Views.Message._MessageResources", typeof(_MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in your registration process. Please try again.
        ///If the problem persists please contact &lt;a href=&quot;mailto:[admin@email.com]&quot;&gt;[admin@email.com]&lt;/a&gt;..
        /// </summary>
        public static string AccountCreationFailed_Message {
            get {
                return ResourceManager.GetString("AccountCreationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AccountCreationFailed_PageTitle {
            get {
                return ResourceManager.GetString("AccountCreationFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when you tried to update you profile. Please try again.
        ///If the problem persists please contact &lt;a href=&quot;mailto:[admin@email.com]&quot;&gt;[admin@email.com]&lt;/a&gt;..
        /// </summary>
        public static string AccountUpdateFailed_Message {
            get {
                return ResourceManager.GetString("AccountUpdateFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AccountUpdateFailed_PageTitle {
            get {
                return ResourceManager.GetString("AccountUpdateFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already been submitted today. Please come back tomorrow. &lt;br&gt;&lt;br&gt;
        ///A contest day is defined as 12:00:00 a.m. to 11:59:59 p.m. Eastern Time (ET)..
        /// </summary>
        public static string AlreadyEntered_Message {
            get {
                return ResourceManager.GetString("AlreadyEntered_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AlreadyEntered_PageTitle {
            get {
                return ResourceManager.GetString("AlreadyEntered_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but an error has occurred when entering your ballot. 
        ///Please try again.  the error persists please contact: &lt;a href=&quot;mailto:[admin@email.com]&quot;&gt;[admin@email.com]&lt;/a&gt;..
        /// </summary>
        public static string BallotError_Message {
            get {
                return ResourceManager.GetString("BallotError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string BallotError_PageTitle {
            get {
                return ResourceManager.GetString("BallotError_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contest ended &lt;strong&gt;[Contest-End-Date]&lt;/strong&gt; at 11:59:59 p.m. EST.  Thanks for participating in the &lt;strong&gt;[Contest-Name]&lt;/strong&gt;!.
        /// </summary>
        public static string ContestClosed_Message {
            get {
                return ResourceManager.GetString("ContestClosed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ContestClosed_PageTitle {
            get {
                return ResourceManager.GetString("ContestClosed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;strong&gt;[Contest-Name]&lt;/strong&gt; opens for submissions on &lt;strong&gt;[Contest-Start-Date]&lt;/strong&gt;!.
        /// </summary>
        public static string ContestNotOpen_Message {
            get {
                return ResourceManager.GetString("ContestNotOpen_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ContestNotOpen_PageTitle {
            get {
                return ResourceManager.GetString("ContestNotOpen_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details:.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authenticate this Facebook Application in order to enter this contest..
        /// </summary>
        public static string FacebookAuthenticationFailed_Message {
            get {
                return ResourceManager.GetString("FacebookAuthenticationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string FacebookAuthenticationFailed_PageTitle {
            get {
                return ResourceManager.GetString("FacebookAuthenticationFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred from your request. Please try again. If the error persists please contact &lt;a href=&quot;mailto:[admin@email.com]&quot;&gt;[admin@email.com]&lt;/a&gt;..
        /// </summary>
        public static string Index_Message {
            get {
                return ResourceManager.GetString("Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the age of majority in your province or territory of residence to participate in the [Contest-Name]..
        /// </summary>
        public static string NotAgeOfMajority_Message {
            get {
                return ResourceManager.GetString("NotAgeOfMajority_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string NotAgeOfMajority_PageTitle {
            get {
                return ResourceManager.GetString("NotAgeOfMajority_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need your parent&apos;s permission. FPO..
        /// </summary>
        public static string ParentalPermission_Message {
            get {
                return ResourceManager.GetString("ParentalPermission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ParentalPermission_PageTitle {
            get {
                return ResourceManager.GetString("ParentalPermission_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered into the contest..
        /// </summary>
        public static string RegistrationSuccessful_Message {
            get {
                return ResourceManager.GetString("RegistrationSuccessful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        public static string RegistrationSuccessful_PageTitle {
            get {
                return ResourceManager.GetString("RegistrationSuccessful_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired due to inactivity. Go to the main Entry page to start the entry process again.  Your session will expire after twenty (20) minutes of inactivity on the site..
        /// </summary>
        public static string SessionLost_Message {
            get {
                return ResourceManager.GetString("SessionLost_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string SessionLost_PageTitle {
            get {
                return ResourceManager.GetString("SessionLost_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you entered does not exist in the online community. 
        ///Please enter another email address.  If the problem persists please contact &lt;a href=&quot;mailto:[admin@email.com]&quot;&gt;[admin@email.com]&lt;/a&gt;..
        /// </summary>
        public static string UserDoesNotExist_Message {
            get {
                return ResourceManager.GetString("UserDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string UserDoesNotExist_PageTitle {
            get {
                return ResourceManager.GetString("UserDoesNotExist_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string WeAreSorry {
            get {
                return ResourceManager.GetString("WeAreSorry", resourceCulture);
            }
        }
    }
}
