//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_contest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _LayoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _LayoutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mm_contest.Views.Shared._LayoutResources", typeof(_LayoutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Modern Media Contest.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MetaImage {
            get {
                return ResourceManager.GetString("MetaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Media Contest.
        /// </summary>
        public static string MetaLinkTitle {
            get {
                return ResourceManager.GetString("MetaLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Media Contest.
        /// </summary>
        public static string MetaSiteName {
            get {
                return ResourceManager.GetString("MetaSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Media Contest.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string NavContact {
            get {
                return ResourceManager.GetString("NavContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.modernmedia.ca/.
        /// </summary>
        public static string NavContactUrl {
            get {
                return ResourceManager.GetString("NavContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string NavPrivacy {
            get {
                return ResourceManager.GetString("NavPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prizes.
        /// </summary>
        public static string NavPrizes {
            get {
                return ResourceManager.GetString("NavPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Rules.
        /// </summary>
        public static string NavRules {
            get {
                return ResourceManager.GetString("NavRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string NavUnsubscribe {
            get {
                return ResourceManager.GetString("NavUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.modernmedia.ca/.
        /// </summary>
        public static string NavUnsubscribeUrl {
            get {
                return ResourceManager.GetString("NavUnsubscribeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Your Profile.
        /// </summary>
        public static string NavUpdateProfile {
            get {
                return ResourceManager.GetString("NavUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.modernmedia.ca/.
        /// </summary>
        public static string NavUpdateProfileUrl {
            get {
                return ResourceManager.GetString("NavUpdateProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string NavUserAgreement {
            get {
                return ResourceManager.GetString("NavUserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunc vel quam eu quam sodales interdum. Proin mollis egestas condimentum. Nunc lobortis tempus aliquet. Pellentesque ullamcorper malesuada molestie. &lt;br&gt;Nulla euismod urna nec nunc rutrum cursus. Etiam at nulla in turpis rutrum eleifend. 2013.
        /// </summary>
        public static string ShortRules {
            get {
                return ResourceManager.GetString("ShortRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Media Contest Template.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
    }
}
