//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm_contest.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _RegistrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _RegistrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mm_contest.Views.Register._RegistrationResource", typeof(_RegistrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm you are the age of majority in your province or territory of residence by declaring your year of birth..
        /// </summary>
        public static string HintYearOfBirth {
            get {
                return ResourceManager.GetString("HintYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the &lt;a href=&quot;/Home/Rules&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; and the &lt;a href=&quot;/Home/Privacy&quot; class=&quot;privacyPopUp&quot;&gt;Privacy Policy&lt;/a&gt; and agree to be bound and abide by them..
        /// </summary>
        public static string LabelAcceptRules {
            get {
                return ResourceManager.GetString("LabelAcceptRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        public static string LabelAddress1 {
            get {
                return ResourceManager.GetString("LabelAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string LabelAddress2 {
            get {
                return ResourceManager.GetString("LabelAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string LabelDateOfBirth {
            get {
                return ResourceManager.GetString("LabelDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        public static string LabelMr {
            get {
                return ResourceManager.GetString("LabelMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        public static string LabelMs {
            get {
                return ResourceManager.GetString("LabelMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Yes&lt;/strong&gt;, I would like to receive MAJESTA’s Treesponsible News to be among the first to hear about exciting news, rewards and savings from MAJESTA. Membership is FREE. To view MAJESTA privacy policy, &lt;a href=&quot;/home/privacypolicypopup&quot; class=&quot;privacyPopUp&quot;&gt;click here&lt;/a&gt;..
        /// </summary>
        public static string LabelOptin {
            get {
                return ResourceManager.GetString("LabelOptin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string LabelPostalCode {
            get {
                return ResourceManager.GetString("LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province:.
        /// </summary>
        public static string LabelProvince {
            get {
                return ResourceManager.GetString("LabelProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the &lt;a href=&quot;/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; and the &lt;a href=&quot;/Home/PrivacyPolicyPopUp&quot; class=&quot;privacyPopUp&quot;&gt;Privacy Policy&lt;/a&gt; and agree to be bound and abide by them..
        /// </summary>
        public static string LabelRules {
            get {
                return ResourceManager.GetString("LabelRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string LabelSalutation {
            get {
                return ResourceManager.GetString("LabelSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string LabelTelephone {
            get {
                return ResourceManager.GetString("LabelTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        public static string LabelYearOfBirth {
            get {
                return ResourceManager.GetString("LabelYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Vote, you must fill out all the information below the first time.         ///The next time you Vote, you can skip this step and enter using just your email address.        ///Remember, you can Vote DAILY and help one of the finalist schools win a customized outdoor classroom, valued at $20,000†!.
        /// </summary>
        public static string Registration_Intro {
            get {
                return ResourceManager.GetString("Registration_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration_PageTitle {
            get {
                return ResourceManager.GetString("Registration_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Denotes Required Field.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address field is required..
        /// </summary>
        public static string ValidationAddress {
            get {
                return ResourceManager.GetString("ValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Official Rules..
        /// </summary>
        public static string ValidationAgreeRules {
            get {
                return ResourceManager.GetString("ValidationAgreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City field is required..
        /// </summary>
        public static string ValidationCity {
            get {
                return ResourceManager.GetString("ValidationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Birth is required..
        /// </summary>
        public static string ValidationDateOfBirth {
            get {
                return ResourceManager.GetString("ValidationDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Day of Birth field is required..
        /// </summary>
        public static string ValidationDayOfBirth {
            get {
                return ResourceManager.GetString("ValidationDayOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationField {
            get {
                return ResourceManager.GetString("ValidationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name field is required..
        /// </summary>
        public static string ValidationFirstName {
            get {
                return ResourceManager.GetString("ValidationFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name field is required..
        /// </summary>
        public static string ValidationLastName {
            get {
                return ResourceManager.GetString("ValidationLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Month of Birth field is required..
        /// </summary>
        public static string ValidationMonthOfBirth {
            get {
                return ResourceManager.GetString("ValidationMonthOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postal Code field is required..
        /// </summary>
        public static string ValidationPostalCode {
            get {
                return ResourceManager.GetString("ValidationPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Province field is required..
        /// </summary>
        public static string ValidationProvince {
            get {
                return ResourceManager.GetString("ValidationProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Salutation field is required..
        /// </summary>
        public static string ValidationSalutation {
            get {
                return ResourceManager.GetString("ValidationSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Telephone field is required..
        /// </summary>
        public static string ValidationTelephone {
            get {
                return ResourceManager.GetString("ValidationTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Year of Birth field is required..
        /// </summary>
        public static string ValidationYearOfBirth {
            get {
                return ResourceManager.GetString("ValidationYearOfBirth", resourceCulture);
            }
        }
    }
}
